//AUTH
export const register = "/register"
export const login = "/login"
export const lupaPassword = "/lupa-password"
export const cek_token = "/chek-token"
export const changePass = "/change-password"
export const apiGelombang = "/gelombangPendaftaran"
export const home = "/home"
//
export const dashboardPeserta = "/dashboard"
export const peserta = "/list-peserta"
export const verifikasiPeserta = "/verifikasi-peserta"
export const biaya = "/biaya"
export const gelombang = "/gelombang"
export const detailPeserta = "/detail-peserta"
export const uploadNilai = "/upload-nilai"
export const nilai = "/nilai"
export const downloadNilai = "/download-Nilai"
export const downloadPeserta = "download-peserta"
export const listpeserta = "/listpeserta"
export const uploadpeserta = "/upload-peserta"
export const detailUser = "/get-peserta"
// UPLOAD
export const uploadExcel = "/upload-file"
export const updateBiodata = "/update-bio"
export const jumlahPerGelombang = "/listBygelombang"
//Download file
export const donwloadbiodata = "/download-file"